### ISSUE TITLE
this.state.changed not changed

### ISSUE THREAD

**Issue by Steiger04** [ioBroker/adapter-react#12]
It seems that this.state.changed always stays true once a change has been made. The comparison with this.savedNative in the updateNativeValue () function always returns changed = true when const changed = this.getIsChanged (native) is called.

**Comment by Steiger04** [comment]
https://user-images.githubusercontent.com/17086944/112210906-8ea33b80-8c1b-11eb-866e-0c6c7e644d00.mp4

**Comment by GermanBluefox** [comment]
Should be fixed now. Please verify
