### ISSUE TITLE
Dependency "@material-ui/icons": "^4.x" is missing in package.json

### ISSUE THREAD

**Issue by Xenon-s** [ioBroker/adapter-react#22]
Dependency "@material-ui/icons": "^4.x" is missing in package.json

```
×  ....\node_modules\@iobroker\adapter-react\GenericApp.js:22:44: Cannot resolve dependency '@material-ui/icons/Close'
  20 | var _IconButton = _interopRequireDefault(require("@material-ui/core/IconButton"));
  21 |
> 22 | var _Close = _interopRequireDefault(require("@material-ui/icons/Close"));
     |                                            ^
  23 |
  24 | var _Prompt = _interopRequireDefault(require("./Prompt"));
  25 |
```

@UncleSamSwiss @AlCalzone

**Comment by oweitman** [comment]
did i left anything?
freshly created adapter. 
same result also with npm run:build:parcel
should i install the dependency by myself?

```
root@iobrokerdev:/opt/iobroker/ioBroker.ovarious# npm run watch:parcel

> iobroker.ovarious@0.0.1 watch:parcel /opt/iobroker/ioBroker.ovarious
> parcel admin/src/index.jsx -d admin/build

Server running at http://localhost:1234 
🚨  /opt/iobroker/ioBroker.ovarious/node_modules/@iobroker/adapter-react/GenericApp.js:22:44: Cannot resolve dependency '@material-ui/icons/Close'
  20 | var _IconButton = _interopRequireDefault(require("@material-ui/core/IconButton"));
  21 |
> 22 | var _Close = _interopRequireDefault(require("@material-ui/icons/Close"));
     |                                            ^
  23 |
  24 | var _Prompt = _interopRequireDefault(require("./Prompt"));
```

**Comment by UncleSamSwiss** [comment]
@AlCalzone I guess, he needs to wait for the next release of create-adapter?

**Comment by AlCalzone** [comment]
@oweitman are you using the latest version of `adapter-react`?

**Comment by oweitman** [comment]
I think. Last week I started the create Adapter Skript with the npx command

**Comment by AlCalzone** [comment]
If you didn't update it, probably not. Run this inside your adapter directory
```
npm i -D @iobroker/adapter-react@latest
```
and try again.

We pin this dependency to a specific version in create-adapter because there were many problems where updates broke the generated adapters.

If your test works, we can update it in the creator.

**Comment by oweitman** [comment]
i already added the icons dependency on adapter level.
now the build is working.
now i look for a solution for the watch command, because
i use a docker container on a remote machine (not wsl on windows)
