### ISSUE TITLE
Dark Theme background and font same color 

### ISSUE THREAD

**Issue by o0shojo0o** [ioBroker/adapter-react#25]
With the dark theme the font is no longer visible because it has the same color as the background 

![image](https://user-images.githubusercontent.com/19333515/125207436-a535d700-e28c-11eb-8d25-33ceaad0a609.png)

  
![image](https://user-images.githubusercontent.com/19333515/125207451-b383f300-e28c-11eb-8bac-535feac045a8.png)

**Comment by GermanBluefox** [comment]
Is it Json Config or custom Admin config or what is that?

**Comment by o0shojo0o** [comment]
This is how it came out of the Adapter Creator, I did not make any change to the design.
Here the repo: https://github.com/o0shojo0o/ioBroker.adguard/

**Comment by GermanBluefox** [comment]
I don't know why it does not work, but you can fix it like this:
https://github.com/ioBroker/ioBroker.cameras/blob/master/src/src/App.js#L99

**Comment by o0shojo0o** [comment]
Great that works and is fully satisfactory for me
