### ISSUE TITLE
Schema jsonConfig.json - potentially missing definitions

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/adapter-react#29]
I linked https://raw.githubusercontent.com/ioBroker/adapter-react/master/schemas/jsonConfig.json to vsCode. vsCode reports the erros whcih seem to be due to missing definitions in schema:

**validatorNoSaveOnError** 
seems to be missing completly

**validator, validatorErrorText, validatorNoSaveOnError**
seems to be missing at table elements (item array of table). Validator is working, so the schema seems to be incorrect. As validatorErrorText does not seem to work the schema might be correct - in this case schema.md at admin is incorrect
                         
**default, hidden**
seem to be missing at table elements (item array of table). 

**options**
seems to be missing at table elements (item array of table) of type "select".

**Comment by crycode-de** [comment]
In table items, most (all?) type specific definitions seams to be missing.
E.g. for `selectSendTo`: `command`, `data`, `jsonData`, `defaultFunc`, `noTranslation` are missing.

`noMultiEdit` is missing completely.

`maxLength` for type text is missing.

The `defaultFunc` and `onChange` object syntax seams to be missing completely. This is used e.g. in linkeddevices [here](https://github.com/Scrounger/ioBroker.linkeddevices/blob/3e5f4833b2db648000dabd696c5d5c3bb50df88f/admin/jsonCustom.json#L18-L23) and [here](https://github.com/Scrounger/ioBroker.linkeddevices/blob/3e5f4833b2db648000dabd696c5d5c3bb50df88f/admin/jsonCustom.json#L53-L60) for example.

**Comment by GermanBluefox** [comment]
This repo is deprecated, please create issues for schema here: https://github.com/ioBroker/adapter-react-v5/issues

**Comment by mcm1957** [comment]
moved ingo https://github.com/ioBroker/adapter-react-v5/issues/24
